### ISSUE TITLE
Jutut back link needed

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#456] opened 2020-01-17 14:58 UTC
(MOOC-Jutut) feedback should have a link back to the chapter from which the feedback was given. At the moment, the link points to the (feedback?) exercise in A+.

A+ API should have exercise links in the form "chapter#exercise-id".

Original in Finnish:

palautteesta backlinkki lukuun, josta palaute jätetty. Tällä hetkellä linkki on tehtävään aplussassa.

Aplussan apissa pitää tehtävä linkki olla muotoa "luku#tehtävä".

**Comment by Mankro** [comment] 2020-05-27 19:09
The original issue description is a bit unclear. Perhaps Juha/O1 course could clarify this. If the problem is that MOOC-Jutut has a link to the feedback exercise in A+, but Juha wants a link to the A+ content chapter that contains the feedback exercise, then this might be easy to fix.

**Comment by jsorva** [comment] 2020-05-27 19:24
> The original issue description is a bit unclear. Perhaps Juha/O1 course could clarify this. If the problem is that MOOC-Jutut has a link to the feedback exercise in A+, but Juha wants a link to the A+ content chapter that contains the feedback exercise, then this might be easy to fix.

Yes, that's right; I'd like a link back to the containing chapter. A link back to the feedback exercise itself isn't particularly convenient. (The feedback exercise in A+ does not provide any additional context beyond what's already in Jutut, although it is possible to follow a further link from the feedback exercise to the chapter. That might not sound like much of a problem, but it actually does make a significant difference to UX when processing large amounts of Jutut feedback and trying to figure out what students mean by each one and thinking about responding.)

**Comment by raphendyr** [comment] 2020-05-28 12:17
I think it should be fine to replace the `html_url` in the API with the correct url, which points to the exercise within the chapter (i.e. one that includes the fragment)

**Comment by Mankro** [comment] 2023-06-13 17:42
Closing as duplicate of the issue https://github.com/apluslms/mooc-jutut/issues/29 (in the mooc-jutut repo like it should be).

**Closed by Mankro** 2023-06-13 17:42 UTC
Labels: type: feature, priority: medium, experience: good first issue, area: API, effort: hours, service: mooc-jutut
