### ISSUE TITLE
The Browse course in {{lang}} does not change the language of the HTML document

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#748] opened 2021-01-11 08:42 UTC
A student who speaks Finnish has been enrolled in a multilingual course, but the student enrolled in the course, using English as the enrollment language.

---
**Profile Language**
![image](https://user-images.githubusercontent.com/10437475/104159251-b2fec280-53f7-11eb-98fe-32f7f5677d5b.png)

---
**Enrollment language**
![image](https://user-images.githubusercontent.com/10437475/104159290-c01bb180-53f7-11eb-8792-2d011398fd51.png)
---

Now, the student tries to access a URL with the parameter `hl=fi` (e.g., http://localhost:8000/def/current/introduction/0X_gallery/?hl=fi). Then, A+ will show the following message.

![image](https://user-images.githubusercontent.com/10437475/104160206-69af7280-53f9-11eb-8f19-07271c426c4f.png)

If the student clicks on the button "Browse the course in English", that page will be reloaded, but the value `lang` will not be changed to English.

![image](https://user-images.githubusercontent.com/10437475/104159632-5cde4f00-53f8-11eb-8439-f1885c423696.png)

The following video shows the use case.
![browse-in-english](https://user-images.githubusercontent.com/10437475/104159898-d6763d00-53f8-11eb-87fd-315a561f0c83.gif)

**Comment by Mankro** [comment] 2021-09-08 15:27
The incorrect `<html lang>` attribute was fixed in this newer issue, which turns out to be duplicate of this:
https://github.com/apluslms/a-plus/issues/870

**Closed by Mankro** 2021-09-08 15:27 UTC
Labels: priority: high, area: linguistic form, type: refactoring, effort: days, experience: moderate, requester: internal
