### ISSUE TITLE
API shows module is open even after it is closed

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1107] opened 2022-12-08 12:13 UTC
As noticed on O1 course, the API at https://plus.cs.aalto.fi/api/v2/courses/249/exercises/ shows `is_open: false` for Week 1, but `is_open: true` for Week 2. Both have closing time in the past (Sep 2022). Also the later weeks show incorrectly that the module is open, even with closing time in the past.

**Comment by Mankro** [comment] 2022-12-08 22:21
If this is caused by our hacky hardcoded "cache" from early September for this specific URL, then there is no issue. We just need to delete the hardcoded alias from the NGINX settings.

**Comment by Mankro** [comment] 2022-12-13 11:42
This was caused by the "hardcoded cache" and it has been fixed in the production servers. No bugs in the source code.

**Closed by Mankro** 2022-12-13 11:42 UTC
Labels: type: bug, area: API, requester: CS, requires: priority
