### ISSUE TITLE
Submission feedback modal can't be scrolled if duplicate submission modal appeared first

### ISSUE THREAD

**Issue by ihalaij1** [apluslms/a-plus#1063] opened 2022-08-23 09:22 UTC
There is an issue with submission feedback modals in chapter exercises; they can't be scrolled up or down if the duplicate submission modal appeared before the exercise was submitted.

**Comment by Mankro** [comment] 2022-08-23 16:28
To clarify, this affects the feedback modal after making a submission if you wait long enough for the feedback to appear. At first, the modal shows the message "accepted for grading, wait a while". The feedback must be long enough so that you can see it does not fit in the browser viewport and then you are unable to scroll it at all. 

If you open the feedback modal afterwards from the My submissions dropdown (in the exercise frame on a chapter page), the scrolling works well. The issue is in the modal that appears automatically after submitting if the duplicate submission confirmation dialog was shown first.

Duplicate submission check refers to #1048. In chapter exercises, if the user submits the same solution again, there is a confirmation dialog "do you really want to submit this again".

**Comment by Mankro** [comment] 2022-08-23 16:32
We have seen the issue at least in Chrome and Safari (browsers).

Note that A+ uses the outdated version 3.4 of Bootstrap. The modal JS and CSS are part of Bootstrap. Bootstrap does not officially support opening multiple modals at the same time. Why would it count as "multiple modals" if you first open the duplicate submission modal, close it from JS code, and then open a new modal from the JS code?

https://getbootstrap.com/docs/3.4/javascript/#modals

The docs say:

> Multiple open modals not supported
>
> Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

**Comment by Mankro** [comment] 2022-10-25 12:29
@ihalaij1 Is this a duplicate of #1093? It feels so.

**Comment by ihalaij1** [comment] 2022-10-25 12:31
> @ihalaij1 Is this a duplicate of #1093? It feels so.

Yes, it is. I did not remember an issue was already created for this.

**Comment by Mankro** [comment] 2022-10-25 13:55
Closing as duplicate of #1093.

**Closed by Mankro** 2022-10-25 13:55 UTC
Labels: type: bug, area: user interface, effort: days, experience: beginner, requester: team, requires: priority
