### ISSUE TITLE
Display DL extension metadata even when folding

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1121] opened 2023-01-03 16:23 UTC
It is extremely common that a student gets a deadline extension for multiple exercises at once. In such cases, the DL extensions table folds the exercises into one entry so that the view doesn’t get cluttered. That’s great, but it would be nice if the metadata — _who granted the extension? when?_ — was shown for the folded items as well (assuming it’s one person and a single time, which should almost always be the case). This does not currently happen. The columns on the right are blank here:

![image](https://user-images.githubusercontent.com/8523129/210397536-7bd45783-2e42-44dc-9dea-935f3f40be08.png)

**Comment by Mankro** [comment] 2023-01-03 16:39
Closing as duplicate of #1046. The pull request #1105 is nearly finished.

**Closed by Mankro** 2023-01-03 16:39 UTC
