### ISSUE TITLE
O1-style personal statistics (e.g. "you've reported a total number of X hours and are about to get a grade of Y") in course-feedback questionnaire has stopped working; must be fixed

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#531] opened 2020-04-18 06:29 UTC
>**Migrated from Trello**

O1-style personal statistics (e.g. "you've reported a total number of X hours and are about to get a grade of Y") in course-feedback questionnaire has stopped working; must be fixed

----

**Conversation**

>**Markku Riekkinen :**
I don't really know what this is about. A specific feedback questionnaire used in O1? Not an A+ feature?
>
>**Juha Sorva :**
Our end-of-course feedback form in A+ has a question about course workload. In the past (until 2017), the question is preceded by a personalized text that says "Kurssimateriaalissa on (viikkokoosteet pois lukien) 56 lukua, joista olet itse kertonut ajankäytöstäsi XXX luvun osalta. Yhteensä ilmoitit käyttäneesi näiden lukujen lukemiseen ja tehtäviin noin YYY tuntia. Kurssiarvosanaksesi on nykyisillä suorituksilla tulossa ZZZ."
>
>(See here: https://plus.cs.hut.fi/o1/2017/k13/osa01/)
>
>XXX, YYY, and ZZZ were automatically generated from the students' self-reported hours and assignment scores.
>
>Teemu S. originally implemented this functionality in Goblin and Teemu L. later implemented it somehow into A+ (don't know the details), but it hasn't worked since Fall 2017.
>
>Currently, O1 is the only course that has (had) this functionality, but I think other courses might benefit from it (either in feedback forms like O1 or somewhere else where they might want to inform students about their reported time usage.)

**Comment by Mankro** [comment] 2020-06-18 17:01
This is very similar to https://github.com/apluslms/a-plus/issues/534, especially when the comment https://github.com/apluslms/a-plus/issues/534#issuecomment-640122183 does not mention the enrollment questionnaire even though the title includes enrollment questions.

**Comment by Mankro** [comment] 2022-06-10 19:22
Closing as duplicate of #534.

**Closed by Mankro** 2022-06-10 19:22 UTC
Labels: type: feature, O1 needs, area: statistics/analysis, effort: days, experience: moderate, area: end-of-course
