### ISSUE TITLE
Approving late submissions in the whole module does not do anything

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#1086] opened 2022-09-20 19:17 UTC
Commit https://github.com/apluslms/a-plus/commit/7c65106714abe63caa1dfe644adf5ab34d3a75c9 added the "approve late/unofficial submissions" feature. Now, O1 J.S. demoed that approving late submissions for the whole module does not do anything.

1. go to the inspect submission page of some late submission (late penalty applied)
2. in the "approve submission" modal dialogue, select "all submissions in the module"
3. after submitting, the green info message in the top of the page says that "0 submissions were approved" and the submissions still have the late penalties.

**Comment by jsorva** [comment] 2022-09-20 21:33
If the fix for this turns out to be simple, please fix it soon, as that would save me (and other large-class teachers, I’m sure) a lot of trouble over the course of the starting semester. Thank you!

**Comment by EerikSaksi** [comment] 2022-09-22 08:41
Hi, I've been trying to reproduce this issue by creating two submissions in the same module, and applying a late penalty to both of them. It seems that I only get the "0 submissions were approved" dialogue with the "approve only unofficial submissions" option selected. Did you have this option selected in the modal dialogue?

https://user-images.githubusercontent.com/46625399/191699263-205c009a-e744-4aa0-a143-836f07fa3fe4.mp4

**Comment by jsorva** [comment] 2022-09-22 09:13
Hi! I get the issue with other settings, too, as illustrated here (sry the mouse cursor is a bit glitchy in this video for some reason, but you get the point).

https://user-images.githubusercontent.com/8523129/191707578-423e4bf9-0aad-44d5-990d-4f02c627bffd.mp4

**Comment by EerikSaksi** [comment] 2022-09-22 10:18
Thanks for confirming, helps me narrow down possible issues

**Comment by EerikSaksi** [comment] 2022-09-23 09:00
I've been writing a test on my local branch and the function seems to be in order. 

https://github.com/EerikSaksi/a-plus/blob/817cde638bad1131da1152a292923c7c15e14775/exercise/tests.py#L1187-L1201

I've been trying to figure out what possible causes there are:

* 'approve-scope' is sent incorrectly for some reason
* The incorrect 'user_id' is sent, and this other user does not have any late submissions
* There isn't a late penalty, but this seems unlikely as you can see the late penalty in the screen recording

**Closed** 2022-09-28 07:09 UTC
Labels: type: bug, priority: high, effort: hours, experience: moderate, requester: CS, area: points/grade
