### ISSUE TITLE
Synchronizing enrollments in Oodi

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#530] opened 2020-04-18 06:19 UTC
>**Migrated from Trello**

Only students enrolled in Oodi should be allowed to enroll in the course. It is still good to have the separate (explicit) enrollment option in A+ as we can have the enrollment questionnaire there. It should not be difficult to implement the feature this way, as the enrollment in Oodi has to be checked only upon enrolling for the same course in A+.

This request comes from the MCC course (Mario).

**Comment by raphendyr** [comment] 2020-04-18 06:30
Requires integration to Oodi/SISU to optain data. Biggest challenge is to pair A+ course to correct course in Oodi/SISU. This is specially challenging, as we do not do any course name validation in A+ to match information any way.

For limiting enrollments, the requirements are bit lower, as we need less trust. If a course would be paired to a wrong course, then students couldn't enroll and some students could enroll, who shouldn't.

So far, A+ has specially tried to avoid pairing to Oodi/SISU due to complexities. In mycourses, this is done other way around. Courses are created based on the data in Oodi/SISU, thus the pairing is implicit. In A+ context, it's assumed that there can be courses outside of Oodi/SISU definitions. Currently, pairing is done manually py the teacher when exporting points. As there is demand to automate this, we may assume that better pairing has to be implemented.

Thus, when implemented for this purpose, the time effort is huge. When some integration is already implemented, the effort should be re-evaluated.

**Comment by Mankro** [comment] 2020-09-08 09:47
Closing as duplicate of https://github.com/apluslms/a-plus/issues/550 (This one refers to Oodi and that one to SISU, but only SISU will be used in the future.)

**Closed by Mankro** 2020-09-08 09:47 UTC
Labels: area: student administration systems, effort: months, priority: high, status: duplicate, type: feature
