### ISSUE TITLE
NUL character in feedback breaks submission page

### ISSUE THREAD

**Issue by piehei** [apluslms/a-plus#316] opened 2018-02-07 11:05 UTC
I think I've located a bug.

When mooc-grader POSTs feedback for a graded submission, a-plus accepts it and stores it in the db. If the feedback text includes a NUL character \x00, the submission view page breaks when showing the feedback.

I've checked the database and the feedback text field includes the NUL in \u0000 format. When the submission page is shown to the user, the page renders until the NUL character and breaks. The right sidebar is rendered after that.

So my guess is this breaks: https://github.com/Aalto-LeTech/a-plus/blob/1f612f7a84233e0242518e50cd108b10fcc5c503/exercise/templates/exercise/submission.html

**Comment by raphendyr** [comment] 2018-02-07 12:09
Null character should be removed before it's stored in the db. Many programs interpret null as end of string. In addition, there is no need to store strings with null characters in A+.

Is there any real use for null character in your case?

**Comment by piehei** [comment] 2018-02-07 12:38
No, definitely no use for it. I would have expected some error msg or whatever instead of accepting it and then failing later on.

I have already fixed our grader tests so that NULs are stripped off in case of student programs producing them.

But this means, in practice, that a-plus can be made to "fail" if given bad input. I think there should be a check before saving grader POST data or smth.

**Comment by raphendyr** [comment] 2018-02-07 12:41
Yep, there should be a check. Btw. do you have any good idea where to clean the information at grader as it too shouldn't send bad data to A+? I would leave changes to how feedback is handled in A+ for later (there are couple of other issues there too).

**Comment by skulonen** [comment] 2021-04-29 14:44
@Mankro This seems to be already fixed. When the grading service returns a feedback string with `NUL` in it, A+ refuses to save it and prints out the following error message:
```
[2021-04-29 17:21:14,150: ERROR/async_views] Exercise service returned with invalid grade request: feedback: Null characters are not allowed.
```
The error message is caused by Django's `ProhibitNullCharactersValidator`, which was added to the `CharField` class in Django 2.0:

https://github.com/django/django/blame/907d3a7ff4e12ad4ccc86af26a728007fe4d6fa2/django/forms/fields.py#L221
https://code.djangoproject.com/ticket/28201

This A+ issue was reported in February 2018. Back then A+ used Django 1.10.

**Comment by Mankro** [comment] 2021-04-29 15:02
Related to https://github.com/apluslms/a-plus/issues/696

**Comment by skulonen** [comment] 2021-04-30 11:05
I noticed that NUL characters will also break exercise scoring, if the grader reports the score by printing "TotalPoints" and "MaxPoints" to stdout. If `/feedback/out` contains a NUL character, it will be considered to be a binary file by grep. This causes the grep calls in `parse_points_from_out` to print `Binary file filewithnull.txt matches`, which causes the string "file" to be assigned to the variables `points` and `max_points`. Further, we can see the effect of this in the data that mooc-grader sends to A+:

```
{'points': ['0'], 'max_points': ['0'], 'grading_data': ['{"errors":"Points \'file\' is not a valid number.\\nMax points \'file\' is not a valid number."}\n'] ...
```

**Comment by Mankro** [comment] 2021-05-04 16:41
I think most graders print points to stdout after printing feedback. It is challenging to print points directly to the separate points file even though the grading-base container supports that file layout. The problem is that when the grader program is started with the `capture` command, the process is no longer allowed to write the points file due to the file permissions. If the `capture` command is not used and the process runs as the root user, then it is easier for the student to cheat and manipulate the points in the submitted code.

**Comment by Mankro** [comment] 2021-05-04 16:51
> I noticed that NUL characters will also break exercise scoring, if the grader reports the score by printing "TotalPoints" and "MaxPoints" to stdout. If /feedback/out contains a NUL character, it will be considered to be a binary file by grep.

@skulonen are you able to fix the problem in the grading-base container or what would you suggest? Should the grading-base scripts first modify the feedback before parsing it? The NUL characters could be changed to the escaped strings `\x00`. The points should not be broken even if the feedback string contains NUL characters.

The grading-base container is part of our "security" against cheating students. Just try to think that you don't open new paths for the student to print their (always full) points and ignore the real grader output.

I suppose you already found the code: 
* https://github.com/apluslms/grading-base/blob/master/bin/grade
* https://github.com/apluslms/grading-base/blob/master/rootfs/gw
* https://github.com/apluslms/grading-base/blob/d20e331f6a44e05bbc238307b6c4d1ac03b975d7/Dockerfile#L48
* https://github.com/apluslms/grading-base/blob/master/README.md

**Comment by skulonen** [comment] 2021-05-05 07:47
@Mankro We could use the `-a`/`--text` option in grep, which causes the file to be treated as a text file regardless of its contents. The points would then get parsed correctly, but the feedback would still get sent to A+ with the null characters, and would need to be replaced in A+ code.

Or like you said, we could modify the file before parsing it. An easy way would be to use cat with the `-v` option, which prints null characters as `^@`, and also gets rid of other control characters similarly. Replacing them with escape sequences like `\x00` would be more difficult but I'm sure we can figure out some way to do it.

**Comment by Mankro** [comment] 2021-05-05 12:37
After the daily we decided:

* Let's now focus on the NUL character and ignore all the other special control characters.
* A+ shall remove NUL characters from the feedback before saving it. Thus, we don't throw away useful feedback when it fails in the database validation due to a single NUL character.
* The grading-base container shall also remove NUL characters in the end of the grade command so that the container is able to parse points even if somebody printed a NUL character.

**Comment by skulonen** [comment] 2021-05-05 14:16
We could replace the NUL characters with `<code>\x00</code>` for a nice visualization:
![image](https://user-images.githubusercontent.com/28843787/117155569-8cf59780-adc5-11eb-92c8-7e3f52a64c47.png)

**Comment by Mankro** [comment] 2021-05-05 14:30
Are you now referring to grading-base or A+? Many courses output only plain text in the feedback and it is wrapped in the `<pre>` element so that line endings and indentation are preserved in the final rendered HTML page. The `<code>` element is not wanted inside a `<pre>` element.

If the exercise run.sh script uses the command `capture pre ...`, then the whole feedback is wrapped inside `<pre>` and the plain text feedback can be formatted with line ends and indentation. The grader program would then output only plain text without any HTML formatting. The `<pre>` element preserves line endings and indentation in the rendered HTML page. The `pre` command is part of the grading-base container.

Does the `pre` command actually escape HTML tags in its input?
https://github.com/apluslms/grading-base/blob/d20e331f6a44e05bbc238307b6c4d1ac03b975d7/bin/pre#L17

**Comment by skulonen** [comment] 2021-05-06 07:01
Ok, let's just replace the null characters with `\x00` and move on. No need to get too fancy with it.

**Closed** 2021-05-06 07:34 UTC
Labels: area: exercises, area: grading interface, effort: hours, experience: moderate, priority: high, service: mooc-grader, type: bug
