### ISSUE TITLE
Hide exercises in the maintenance mode from the course table of contents

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#438] opened 2020-01-17 12:21 UTC
Exercises in maintenance mode (LearningObject.status maintenance) should be hidden from course table of contents.

Exercises with the status hidden are already hidden in the table of contents. The maintenance mode could be handled in the code in the same way.

**Comment by Mankro** [comment] 2023-05-30 10:19
Closing as duplicate of #1124.

**Closed by Mankro** 2023-05-30 10:19 UTC
Labels: type: bug, area: user interface, priority: medium, area: navigation, effort: hours, experience: beginner, requester: CS
